// Generated by scripts/scrape-courses.py — course content migrated from faremoana.ch.
// Re-run the script to refresh; edit catalog.ts to override individual fields.
import { CatalogNode } from '../models/content.models';

export const COURSE_DETAILS: Record<string, Partial<CatalogNode>> = {
  "/formations-loisirs/enfants/padi-bubblemaker": {
    "related": [
      "/formations-loisirs/enfants/padi-seal-team"
    ],
    "videoId": "Ad5iorC7xlo",
    "introList": [
      "Faire l’expérience de la plongée sous l’attention et la supervision directes d’un PADI Pro,",
      "Prendre leurs premières respirations sous-marines dans une eau moins profonde que 2 mètres / 6 pieds,",
      "Découvrir et apprendre à utiliser l’équipement de plongée conçu pour les enfants – pas celui pour les adultes,",
      "Bien s’amuser."
    ],
    "included": [
      "Introduction théorique",
      "1 entrée et plongée en piscine (sur Genève seulement)",
      "Équipement de plongée",
      "Diplôme"
    ],
    "prices": [
      {
        "label": "PADI Bubblemaker",
        "amount": "CHF 90"
      }
    ],
    "image": "images/courses/padi-bubblemaker.webp"
  },
  "/formations-loisirs/enfants/padi-seal-team": {
    "related": [
      "/formations-loisirs/enfants/padi-master-seal-team",
      "/formations-loisirs/debutants/padi-open-water-diver"
    ],
    "videoId": "Ad5iorC7xlo",
    "intro": [
      "Vous êtes-vous déjà demandé à quoi ça ressemble de descendre sous l’eau avec des lampes de plongée, de prendre des photos sous-marines numériques ou de flotter sans effort comme un astronaute? Vous apprendrez les techniques de plongée de base, mais il y a également des AquaMissions de spécialité, telles que la plongée sur épave, l’orientation, la flottabilité, la protection de l’environnement et plus encore. Avec le PADI Seal Team vous allez faire des activités vraiment cool en piscine, rencontrer des amis et partager l’aventure du monde sous-marin.",
      "Le programme PADI Seal Team enseigne la responsabilité et le respect à l’égard du monde aquatique. Il est divisé en deux parties :"
    ],
    "introList": [
      "La première partie, les AquaMissions 1 à 5, couvre les techniques de plongée de base, comme respirer sous l’eau, vider un masque rempli d’eau, récupérer un détendeur et nager en ressentant l’apesanteur. Chaque séance dure environ une heure. Complétez ces AquaMissions et devenez un Membre PADI Seal Team reconnu. Votre expérience peut être validée pour le cours PADI Open Water Diver quand vous atteignez l’âge pour participer au cours.",
      "Pour la deuxième partie, visitez la page Master Seal Team"
    ],
    "included": [
      "Introduction théorique",
      "Entrées et plongées en piscine",
      "Équipement de plongée",
      "Diplôme",
      "Kit Seal Team (DVD, manuel, autocollants, logbook)"
    ],
    "prices": [
      {
        "label": "PADI Seal Team",
        "amount": "CHF 650"
      }
    ],
    "image": "images/courses/padi-seal-team.webp",
    "cardImage": "images/courses/card-padi-seal-team.webp"
  },
  "/formations-loisirs/enfants/padi-master-seal-team": {
    "related": [
      "/formations-loisirs/debutants/padi-open-water-diver"
    ],
    "videoId": "Ad5iorC7xlo",
    "intro": [
      "Fait la deuxième partie du cours PADI Seal Team et tu rejoindras un groupe d’élite de jeunes plongeurs !",
      "La deuxième partie, 10 Spécialités AquaMissions, inclut des aventures comme l’identification de créatures, la recherche et la récupération d’objets et la plongée libre. Remplis toutes les Spécialités, et tu deviendras un PADI Master Seal Team et rejoindras un groupe d’élite de jeunes plongeurs."
    ],
    "included": [
      "Entrées et plongées en piscine",
      "Équipement de plongée",
      "Diplôme"
    ],
    "prices": [
      {
        "label": "PADI Master Seal Team",
        "amount": "CHF 550"
      }
    ],
    "image": "images/courses/padi-master-seal-team.webp",
    "cardImage": "images/courses/card-padi-master-seal-team.webp"
  },
  "/formations-loisirs/debutants/padi-discover-scuba-diving-piscine-initiation": {
    "related": [
      "/formations-loisirs/debutants/padi-discover-scuba-diving-lac-initiation",
      "/formations-loisirs/debutants/padi-scuba-diver",
      "/formations-loisirs/debutants/padi-open-water-diver"
    ],
    "videoId": "hEI1bdHShyU",
    "intro": [
      "Une introduction rapide et facile à ce qu’il faut pour explorer le monde sous-marin. Bien que ce ne soit pas un cours de certification de plongée, vous apprendrez toutes les étapes nécessaires pour être un plongeur certifié PADI.",
      "Vous êtes-vous toujours demandé quel effet cela fait de respirer sous l’eau ? Si vous voulez essayer la plongée sous-marine, mais que vous n’êtes pas tout à fait prêt à franchir le pas pour suivre un cours de certification, alors le Discover Scuba Diving est fait pour vous.",
      "Vous apprendrez les directives et les techniques de sécurité de base nécessaires pour plonger sous la supervision directe d’un professionnel PADI. Soyez prêt à :"
    ],
    "introList": [
      "Passer en revue le matériel de plongée que vous utilisez pour plonger et à découvrir avec quelle la facilité vous vous déplacer sous l’eau avec votre équipement.",
      "Découvrir quel effet cela fait de respirer sous l’eau.",
      "Apprendre les techniques clés que vous utiliserez lors de chaque plongée sous-marine.",
      "Vous amuser à nager et à explorer.",
      "Voir comment devenir un plongeur certifié en suivant le cours PADI Open Water Diver ."
    ],
    "included": [
      "Introduction théorique",
      "1 Entrée et plongée en piscine* (sur Genève seulement)",
      "Équipement de plongée",
      "Carnet du DSD"
    ],
    "prices": [
      {
        "label": "PADI Discover Scuba Diving (Piscine)",
        "amount": "CHF 90"
      }
    ],
    "image": "images/courses/padi-discover-scuba-diving-piscine-initiation.webp"
  },
  "/formations-loisirs/debutants/padi-discover-scuba-diving-lac-initiation": {
    "related": [
      "/formations-loisirs/debutants/padi-scuba-diver",
      "/formations-loisirs/debutants/padi-open-water-diver"
    ],
    "videoId": "cPstSo2tgSc",
    "intro": [
      "Une introduction rapide et facile à ce qu’il faut pour explorer le monde sous-marin. Bien que ce ne soit pas un cours de certification de plongée, vous apprendrez toutes les étapes nécessaires pour être un plongeur certifié PADI.",
      "Vous êtes-vous toujours demandé quel effet cela fait de respirer sous l’eau? Si vous voulez essayer la plongée sous-marine, mais que vous n’êtes pas tout à fait prêt à franchir le pas pour suivre un cours de certification, alors le Discover Scuba Diving est fait pour vous.",
      "Vous apprendrez les directives et les techniques de sécurité de base nécessaires pour plonger sous la supervision directe d’un professionnel PADI. Soyez prêt à :"
    ],
    "introList": [
      "Passer en revue le matériel de plongée que vous utilisez pour plonger et à découvrir avec quelle la facilité vous vous déplacer sous l’eau avec votre équipement.",
      "Découvrir quel effet cela fait de respirer sous l’eau.",
      "Apprendre les techniques clés que vous utiliserez lors de chaque plongée sous-marine.",
      "Vous amuser à nager et à explorer.",
      "Voir comment devenir un plongeur certifié en suivant le cours PADI Open Water Diver ."
    ],
    "included": [
      "Introduction théorique",
      "1 Plongée en milieu naturel (Lac)",
      "Équipement de plongée"
    ],
    "prices": [
      {
        "label": "PADI Discover Scuba Diving (Lac)",
        "amount": "CHF 100"
      }
    ],
    "image": "images/courses/padi-discover-scuba-diving-lac-initiation.webp",
    "cardImage": "images/courses/card-padi-discover-scuba-diving-lac-initiation.webp"
  },
  "/formations-loisirs/debutants/padi-scuba-diver": {
    "related": [
      "/formations-loisirs/debutants/padi-open-water-diver"
    ],
    "videoId": "KvZT3etZIsw",
    "intro": [
      "Le cours PADI Scuba Diver est une partie du cours PADI Open Water Diver. Si vous disposez de peu de temps, mais voulez vraiment devenir un plongeur, la qualification PADI Scuba Diver peut vous convenir – en particulier si vous vous préférez plonger avec un guide de plongée.",
      "Les PADI Scuba Divers sont qualifiés pour :",
      "Le cours PADI Scuba Diver se compose de trois phases principales :"
    ],
    "introList": [
      "Plonger sous la supervision directe d’un professionnel PADI à une profondeur maximale de 12 mètres/40 pieds",
      "Faire remplir ses bouteilles d’air, louer ou acheter de l’équipement de plongée et participer à des activités de plongée sous supervision",
      "Poursuivre la formation de plongée en complétant la certification PADI Open Water Diver et suivre certains cours de spécialités .",
      "Développement des connaissances en ligne afin de comprendre les principes de base de la plongée sous-marine – seulement les trois premières des cinq sections du cours Open Water Diver .",
      "Plongées en milieu protégé pour apprendre les techniques de plongée de base – seulement les trois premières des cinq plongées du cours Open Water Diver .",
      "Plongées en milieu naturel pour utiliser vos techniques de plongée et faire de l’exploration – seulement deux des quatre plongées du cours Open Water Diver ."
    ],
    "included": [
      "Entrées en piscine",
      "Équipement de plongée",
      "Accès E-learning",
      "Carnet de plongée",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Scuba Diver",
        "amount": "CHF 550"
      }
    ],
    "image": "images/courses/padi-scuba-diver.webp",
    "cardImage": "images/courses/card-padi-scuba-diver.webp"
  },
  "/formations-loisirs/debutants/padi-open-water-diver": {
    "related": [
      "/formations-loisirs/avances/padi-adventure-diver",
      "/formations-loisirs/avances/padi-advanced-open-water-diver",
      "/formations-loisirs/remise-a-niveau/padi-reactivate-piscine",
      "/formations-loisirs/specialites-padi/padi-enriched-air-diver-nitrox",
      "/formations-loisirs/specialites-padi/padi-combinaison-etanche"
    ],
    "videoId": "KvZT3etZIsw",
    "intro": [
      "Si vous avez toujours voulu faire de la plongée sous-marine, l’expérience d’une aventure inégalée et voir le monde sous les vagues, c’est ici que cela commence. Obtenez votre certification de plongée sous-marine avec le cours PADI Open Water Diver – le cours de plongée le plus populaire et le plus largement reconnu dans le monde. Des millions de personnes ont appris la plongée sous-marine avec ce cours et continuent à découvrir les merveilles du monde aquatique.",
      "Ce cours enseigne aux élèves les bases fondamentales et les connaissances nécessaires à la pratique de la plongée. Il permet aux plongeurs certifiés d’explorer les fonds aquatiques jusqu’à une profondeur de 18m. Il offre également la possibilité de participer à certains cours de Spécialités ainsi qu’au cours d’ Advanced Open Water Diver .",
      "Le cours PADI Open Water Diver se compose de trois phases principales :"
    ],
    "introList": [
      "Développement des connaissances ( en ligne , étude indépendante ou en salle de classe) afin de comprendre les principes de base de la plongée sous-marine",
      "Plongées en milieu protégé pour apprendre les techniques de plongée de base",
      "Plongées en milieu naturel pour utiliser vos techniques de plongée et faire de l’exploration !"
    ],
    "included": [
      "Entrées et plongées en piscine",
      "Équipement de plongée",
      "Accès E-learning",
      "Carnet de plongée",
      "Certification"
    ],
    "prices": [
      {
        "label": "Open Water Diver \"Standard\"",
        "amount": "CHF 840"
      },
      {
        "label": "Open Water Diver \"Dry\"",
        "amount": "CHF 1'100",
        "note": "inclus la Spécialité Étanche"
      },
      {
        "label": "Open Water Diver “Referral”",
        "amount": "CHF 470",
        "note": "pour commencer sa formation en piscine et la terminer en mer"
      }
    ],
    "image": "images/courses/padi-open-water-diver.webp",
    "cardImage": "images/courses/card-padi-open-water-diver.webp"
  },
  "/formations-loisirs/avances/padi-dld-plongee-guidee": {
    "related": [
      "/formations-loisirs/avances/padi-adventure-diver",
      "/formations-loisirs/avances/padi-advanced-open-water-diver",
      "/formations-loisirs/specialites-padi/padi-orientation-sous-marine",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite",
      "/formations-loisirs/specialites-padi/padi-plongee-profonde"
    ],
    "videoId": "jFT4HE7yjKM",
    "intro": [
      "Profitez d’un guide de plongée professionnel pour vous aider à mieux comprendre l’environnement de plongée local afin de pouvoir mieux profiter de l’aventure.",
      "Vous souvenez-vous de votre Instructeur PADI disant : “Si vous voyagez vers une nouvelle destination ou visitez un environnement de plongée que vous ne connaissez pas, obtenez une présentation de l’environnement local.” C’est un bon conseil, facile à suivre. Plonger avec un professionnel expérimenté en plongée locale vous permet d’être détendu et de mieux profiter de votre aventure de plongée."
    ],
    "included": [
      "Introduction théorique",
      "1 Plongée en milieu naturel (Lac)",
      "Équipement de plongée"
    ],
    "prices": [
      {
        "label": "PADI DLD (Plongée d’exploration guidée)",
        "amount": "CHF 100",
        "note": "En combinaison humide"
      },
      {
        "label": "PADI DLD (Plongée d’exploration guidée)",
        "amount": "CHF 150",
        "note": "En combinaison étanche"
      }
    ],
    "image": "images/courses/padi-dld-plongee-guidee.webp"
  },
  "/formations-loisirs/avances/padi-adventure-diver": {
    "related": [
      "/formations-loisirs/avances/padi-advanced-open-water-diver",
      "/formations-loisirs/specialites-padi/padi-enriched-air-diver-nitrox",
      "/formations-loisirs/specialites-padi/padi-combinaison-etanche"
    ],
    "videoId": "tWPGi52nkHg",
    "intro": [
      "Le cours Adventure Diver fait partie du programme PADI Advanced Open Water Diver.",
      "Si vous êtes intéressé par des plongées aventure telles que la plongée de nuit ou en combinaison étanche, ce cours offre une variété d’options pour les découvrir. En complétant trois plongées Adventure Dives, vous obtiendrez la certification Adventure Diver, qui vous permettra de travailler avec votre instructeur pour améliorer vos compétences en plongée et augmenter votre confiance en vous. C’est une excellente opportunité pour découvrir vos préférences et pour maximiser votre plaisir en plongée.",
      "En outre, chaque plongée Adventure Dive peut être créditée comme la première plongée pour un cours PADI Specialty Diver correspondant. Si vous avez déjà suivi un cours de spécialité, vous pouvez demander à votre instructeur si vous êtes admissible à un crédit pour une plongée Adventure Dive."
    ],
    "included": [
      "Théorie en ligne",
      "3 Plongées en milieu naturel",
      "Équipement de plongée",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Adventure Diver",
        "amount": "CHF 450"
      }
    ],
    "image": "images/courses/padi-adventure-diver.webp",
    "cardImage": "images/courses/card-padi-adventure-diver.webp"
  },
  "/formations-loisirs/avances/padi-advanced-open-water-diver": {
    "related": [
      "/formations-loisirs/avances/padi-rescue-diver",
      "/formations-loisirs/specialites-padi/padi-plongee-profonde",
      "/formations-loisirs/specialites-padi/padi-orientation-sous-marine",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite"
    ],
    "videoId": "k8m8eoMOf18",
    "intro": [
      "Ce cours peut être suivi après avoir complété la certification PADI Open Water Diver. Il s’intitule PADI Advanced Open Water Diver, car il vous permet de faire progresser vos connaissances et vos compétences de plongée.",
      "Exploration, émotions et expériences ! Voilà en quoi consiste le cours Advanced Open Water Diver PADI. Vous n’avez pas besoin d’être un expert pour le suivre – il est conçu pour vous faire avancer en plongée, ainsi vous pouvez commencer directement après avoir obtenu votre certification PADI Open Water Diver. Le cours vous permet de développer votre confiance en vous et d’améliorer vos techniques lors de différentes plongées Adventure Dives. Vous essayez différentes spécialités en acquérant de l’expérience sous la supervision de votre instructeur PADI.",
      "Vous planifiez votre parcours d’apprentissage avec votre instructeur en choisissant vos plongées parmi une longue liste d’Adventure Dive. Il y a deux plongées obligatoires : Profonde (30 mètres) et Orientation et vous en choisissez trois autres.",
      "Obtenez un crédit ! Chaque plongée Adventure Dive peut être créditée pour la première plongée du cours PADI Specialty Diver correspondant. Si vous avez déjà suivi un cours de spécialité, demandez à votre instructeur si vous bénéficiez d’un crédit pour une plongée Adventure Dive."
    ],
    "included": [
      "Théorie en ligne",
      "5 plongées en milieu naturel",
      "Équipement de plongée",
      "Certification"
    ],
    "prices": [
      {
        "label": "AOWD \"Standard\"",
        "amount": "CHF 610"
      },
      {
        "label": "AOWD \"Dry\"",
        "amount": "CHF 900",
        "note": "inclus la Spécialité Étanche"
      },
      {
        "label": "AOWD \"Deep\"",
        "amount": "CHF 900",
        "note": "inclus la Spécialité Profonde"
      }
    ],
    "image": "images/courses/padi-advanced-open-water-diver.webp",
    "cardImage": "images/courses/card-padi-advanced-open-water-diver.webp"
  },
  "/formations-loisirs/avances/padi-rescue-diver": {
    "related": [
      "/formations-loisirs/padi-master-scuba-diver",
      "/secourisme/padi-emergency-first-response",
      "/secourisme/padi-oxygen-provider"
    ],
    "videoId": "YNdo9tcgzpM",
    "intro": [
      "Apprenez à prévenir et à gérer les problèmes dans l’eau et à avoir davantage confiance en vos compétences de plongeur. C’est un cours exigeant, mais très gratifiant.",
      "Les plongeurs décrivent le cours de Rescue Diver PADI comme le plus grand défi, mais le plus gratifiant qu’ils aient jamais vécu. Pourquoi ? Parce que vous apprenez à prévenir et à gérer les problèmes dans l’eau, et à avoir davantage confiance en vos compétences de plongeur, sachant que vous pouvez aider les autres en cas de besoin. Pendant le cours, vous apprenez à devenir un meilleur binôme en pratiquant les exercices de résolution de problèmes jusqu’à ce que cela devienne un réflexe.",
      "Le cours PADI Rescue Diver vous prépare à faire face à des situations d’urgence mineures ou graves en plongée, en utilisant diverses techniques. Lors du développement des connaissances et des exercices de sauvetage, vous apprenez à détecter un problème et à y répondre. Pendant les scénarios de sauvetage, vous mettez en pratique vos connaissances et vos techniques. Les sujets traités comprennent :"
    ],
    "introList": [
      "Auto-sauvetage",
      "Reconnaître et gérer le stress chez les autres plongeurs",
      "Gestion et équipement d’urgence",
      "Sauvetage de plongeurs paniqués",
      "Sauvetage de plongeurs inconscients"
    ],
    "included": [
      "Théorie en ligne",
      "Entrées en piscine",
      "Équipement de plongée",
      "Certification"
    ],
    "prices": [
      {
        "label": "Rescue Diver \"Standard\"",
        "amount": "CHF 800"
      },
      {
        "label": "Rescue Diver \"Spécial\"",
        "amount": "CHF 1'050",
        "note": "inclus la formation Emergency First Response et un pocket mask"
      },
      {
        "label": "Rescue Diver \"Deluxe\"",
        "amount": "CHF 1'200",
        "note": "inclus la formation Emergency First Response, la Spécialité Oxygen Provider"
      }
    ],
    "image": "images/courses/padi-rescue-diver.webp",
    "cardImage": "images/courses/card-padi-rescue-diver.webp"
  },
  "/formations-loisirs/padi-master-scuba-diver": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite",
      "/formations-loisirs/specialites-padi/padi-plongee-profonde",
      "/formations-loisirs/specialites-padi/padi-plongee-de-nuit",
      "/formations-loisirs/specialites-padi/padi-enriched-air-diver-nitrox",
      "/formations-loisirs/specialites-padi/padi-plongee-sous-glace"
    ],
    "videoId": "dpLyLhpv6vo",
    "intro": [
      "Il s’agit de la qualification de plongeur loisir la plus élevée au sein du programme PADI. Elle est la preuve d’une maîtrise et de compétences élevées.",
      "Afin d’obtenir la qualification de Master Scuba Diver, le plongeur doit avoir 5 Spécialités certifiées, avoir un minimum de 50 plongées enregistrées et être Rescue Diver."
    ],
    "included": [
      "Âge requis : 12 ans révolus (Junior) 15 ans révolus",
      "Être Rescue Diver",
      "Avoir sa carte de certification",
      "Avoir 5 Spécialités certifiées",
      "Avoir un minimum de 50 plongées enregistrées"
    ],
    "image": "images/courses/padi-master-scuba-diver.webp",
    "cardImage": "images/courses/card-padi-master-scuba-diver.webp"
  },
  "/formations-loisirs/specialites-padi/padi-enriched-air-diver-nitrox": {
    "related": [
      "/formations-loisirs/avances/padi-advanced-open-water-diver",
      "/formations-loisirs/specialites-padi/padi-combinaison-etanche",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite"
    ],
    "videoId": "0HR6PLfXn5k",
    "intro": [
      "Le cours de spécialité PADI le plus populaire ! Plonger avec l’air enrichi augmente votre temps de plongée sans décompression, particulièrement lors de plongées successives.",
      "Le cours de plongée à l’air enrichi (Enriched Air Diver) est la spécialité PADI la plus populaire. Pour quelle raison ? Parce que la plongée à l’air enrichi Nitrox vous autorise un temps de non-décompression plus long, spécialement pour les plongées successives (croisière, voyage, etc.). Si rester plus longtemps sous l’eau et y retourner au plus vite vous intéressent, n’hésitez pas, devenez plongeur à l’air enrichi.",
      "Vous apprendrez pourquoi la plongée avec de l’air dont le pourcentage en oxygène est plus élevé et celui en azote moins élevé vous autorise un temps de plongée plus long. Vous verrez également les considérations sur l’équipement liées à l’air enrichi. Pendant une séance pratique, vous :",
      "La plongée à l’air enrichi permet de réduire l’exposition à l’azote et donc d’augmenter la sécurité et le confort de la plongée, particulièrement lors de plongées successives (croisière, voyage, etc.)."
    ],
    "introList": [
      "Discuterez de la gestion de l’exposition à l’oxygène.",
      "Analyserez le pourcentage en oxygène du gaz contenu dans votre bouteille de plongée.",
      "Règlerez votre ordinateur pour la plongée à l’air enrichi Nitrox."
    ],
    "included": [
      "Théorie en ligne",
      "1 atelier pratique",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Enriched Air Diver (Nitrox)",
        "amount": "CHF 250"
      }
    ],
    "image": "images/courses/padi-enriched-air-diver-nitrox.webp",
    "cardImage": "images/courses/card-padi-enriched-air-diver-nitrox.webp"
  },
  "/formations-loisirs/specialites-padi/padi-combinaison-etanche": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-plongee-sous-glace",
      "/formations-loisirs/specialites-padi/padi-orientation-sous-marine",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite"
    ],
    "videoId": "vmjVQs-ee5E",
    "introList": [
      "Mettre et enlever votre combinaison étanche avec un minimum d’assistance.",
      "Maîtriser le contrôle de la flottabilité en utilisant votre combinaison étanche.",
      "Les procédures de plongée en sécurité en utilisant une combinaison étanche."
    ],
    "included": [
      "Théorie",
      "2 plongées en milieu naturel",
      "Le prêt d’une combinaison étanche",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Combinaison Étanche",
        "amount": "CHF 400"
      }
    ],
    "image": "images/courses/padi-combinaison-etanche.webp",
    "cardImage": "images/courses/card-padi-combinaison-etanche.webp"
  },
  "/formations-loisirs/specialites-padi/padi-orientation-sous-marine": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-combinaison-etanche",
      "/formations-loisirs/specialites-padi/padi-plongee-de-nuit",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite"
    ],
    "videoId": "-ws41cRuokM",
    "intro": [
      "Affinez vos compétences en matière d’observation sous-marine et apprenez à utiliser votre boussole avec plus de précision.",
      "Soyez le plongeur que tout le monde veut suivre, parce que vous savez où vous êtes et où vous allez. Le cours d’Orientation sous-marine PADI (Underwater Navigator) vous apprend à peaufiner vos techniques d’observation et à utiliser votre boussole avec plus de précision sous l’eau. Si vous aimez les défis avec de grandes récompenses, suivez ce cours et amusez-vous à trouver votre chemin.",
      "Vous étudierez les techniques de circonstance, incluant l’orientation en prenant des repères naturels et en utilisant un compas. Lors de trois plongées scaphandre, vous apprendrez à :",
      "La première plongée de cette Spécialité PADI peut être validée comme Plongée Adventure Dive pour votre brevet Advanced Open Water Diver – n’hésitez pas à nous demander pour obtenir le crédit de la plongée"
    ],
    "introList": [
      "Utiliser les techniques d’estimation de la distance sous l’eau.",
      "Naviguer au compas en faisant au moins cinq changements de cap.",
      "Marquer ou retrouver un objet immergé ou prendre les coordonnées en s’aidant de repères en surface",
      "Cartographier un parcours de plongée."
    ],
    "included": [
      "Théorie",
      "3 plongées en milieu naturel",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Orientation sous-marine",
        "amount": "CHF 350"
      }
    ],
    "image": "images/courses/padi-orientation-sous-marine.webp",
    "cardImage": "images/courses/card-padi-orientation-sous-marine.webp"
  },
  "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-orientation-sous-marine",
      "/formations-loisirs/specialites-padi/padi-parachute-de-palier",
      "/formations-loisirs/specialites-padi/padi-recherche-et-recuperation-dobjets"
    ],
    "videoId": "nsh3xOWESpM",
    "introList": [
      "Comment configurer votre matériel de plongée – afin d’être parfaitement équilibré sous l’eau.",
      "Ajuster précisément son lestage – pour être ni trop lourd ni trop léger, même de quelques grammes.",
      "Hydrodynamisme – pour économiser l’air et se déplacer avec aisance sous l’eau.",
      "Faire le ludion sans effort – en position verticale et horizontale."
    ],
    "included": [
      "Théorie",
      "2 plongées en milieu naturel",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Maîtrise de la flottabilité",
        "amount": "CHF 300"
      }
    ],
    "image": "images/courses/padi-maitrise-de-la-flottabilite.webp",
    "cardImage": "images/courses/card-padi-maitrise-de-la-flottabilite.webp"
  },
  "/formations-loisirs/specialites-padi/padi-plongee-profonde": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-combinaison-etanche",
      "/formations-loisirs/specialites-padi/padi-plongee-de-nuit",
      "/formations-loisirs/specialites-padi/padi-orientation-sous-marine"
    ],
    "videoId": "BR6r-FE6ekQ",
    "intro": [
      "Explorez des sites de plongées plus profondes avec confiance jusqu’à des profondeurs de 40 mètres. Apprenez à gérer votre réserve d’air, à revoir les procédures de contact avec votre binôme et à contrôler votre flottabilité.",
      "L’attrait des profondeurs. Il y a quelque chose de fascinant et de mystérieux à explorer les sites de plongée plus profonds. Parfois, c’est une épave qui vous attire au-delà de 18 mètres/60 pieds, ou le long d’un tombant, c’est peut-être une énorme gorgone ou une éponge géante. Quoi qu’il en soit, pour plonger en toute confiance à des profondeurs allant jusqu’à 40 mètres/130 pieds, vous devriez suivre la Spécialité Plongée profonde PADI (Deep Diver).",
      "Votre formation commencera par une discussion sur les raisons pour plonger profond et sur l’importance de connaître vos limites personnelles. Lors de quatre plongées profondes avec votre instructeur, vous étudierez :"
    ],
    "introList": [
      "L’équipement spécialisé pour la plongée profonde.",
      "La planification de plongées profondes, les procédures pour maintenir le contact entre binômes et le contrôle de la flottabilité.",
      "La gestion de votre réserve de gaz et de la narcose à l’azote et les considérations liées à la sécurité."
    ],
    "included": [
      "Théorie",
      "4 plongées en milieu naturel",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Plongée Profonde",
        "amount": "CHF 400"
      }
    ],
    "image": "images/courses/padi-plongee-profonde.webp",
    "cardImage": "images/courses/card-padi-plongee-profonde.webp"
  },
  "/formations-loisirs/specialites-padi/padi-plongee-de-nuit": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-orientation-sous-marine",
      "/formations-loisirs/specialites-padi/padi-enriched-air-diver-nitrox",
      "/formations-loisirs/specialites-padi/padi-recherche-et-recuperation-dobjets"
    ],
    "videoId": "vmjVQs-ee5E",
    "intro": [
      "Le monde sous-marin change à mesure que les créatures diurnes se retirent et que les organismes nocturnes émergent. Si vous vous êtes demandé ce qui se passe sous l’eau après le coucher du soleil, inscrivez-vous au cours de spécialité de plongée nuit PADI.",
      "Plonger la nuit sous la surface de l’eau semble étrange, et pourtant tellement attrayant. Même si vous avez plongé sur un site à maintes reprises, la nuit, vous découvrez un tout nouveau monde et l’observez prendre vie à la lueur de votre lampe de plongée. La scène change au fur et à mesure que les créatures diurnes se retirent et que les organismes nocturnes émergent. Si vous vous demandez ce qui se passe sous l’eau après le coucher du soleil, inscrivez-vous à la Spécialité Plongée de nuit (Night Diver).",
      "La Spécialité Plongée de nuit vous apprend à vous concentrer sur ce que vous voyez dans le faisceau de votre lampe, sur le contrôle de votre flottabilité sans avoir de repère, sur le maintien du contact avec votre binôme et sur certains détails qui vous pourriez ignorer pendant la journée. Lors de trois plongées de nuit, vous apprendrez à :",
      "Aussi, la première plongée de cette Spécialité PADI peut être validée comme Plongée Adventure Dive pour votre brevet Advanced Open Water Diver – demandez nous pour obtenir le crédit de la plongée."
    ],
    "introList": [
      "Utiliser une lampe de plongée et les techniques de communication.",
      "Vous mettre à l’eau, sortir de l’eau et vous orienter dans l’obscurité.",
      "Identifier de quelle façon les plantes et les animaux diffèrent ou changent de comportement la nuit."
    ],
    "included": [
      "Théorie",
      "3 plongées en milieu naturel",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Plongée de nuit",
        "amount": "CHF 350"
      }
    ],
    "image": "images/courses/padi-plongee-de-nuit.webp",
    "cardImage": "images/courses/card-padi-plongee-de-nuit.webp"
  },
  "/formations-loisirs/specialites-padi/padi-recherche-et-recuperation-dobjets": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-parachute-de-palier",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite"
    ],
    "videoId": "vmjVQs-ee5E",
    "introList": [
      "La planification, l’organisation, les procédures, les techniques, la gestion de problèmes et les risques impliqués lorsqu’on recherche et remonte des objets en surface.",
      "Les techniques appropriées pour localiser des petits et grands objets en utilisant des schémas de recherche.",
      "Comment utiliser un parachute de relevage et d’autres méthodes de récupération.",
      "Les techniques de recherche en cas de visibilité réduite."
    ],
    "included": [
      "Théorie",
      "4 plongées en milieu naturel",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Recherche et Récupération d’Objets",
        "amount": "CHF 400"
      }
    ],
    "image": "images/courses/padi-recherche-et-recuperation-dobjets.webp",
    "cardImage": "images/courses/card-padi-recherche-et-recuperation-dobjets.webp"
  },
  "/formations-loisirs/specialites-padi/padi-plongee-en-altitude": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-parachute-de-palier",
      "/formations-loisirs/specialites-padi/padi-plongee-sous-glace"
    ],
    "videoId": "vmjVQs-ee5E",
    "intro": [
      "Imaginez-vous plonger sous la surface d’un lac de montagne limpide pour explorer une épave bien préservée. Intéressé ? Chaque fois que vous plongez à une altitude de 300 mètres/1000 pieds, ou plus, au-dessus du niveau de la mer, vous faites de la plongée en altitude. Si vous êtes prêt à découvrir un monde caché où peu se sont aventurés, alors la Spécialité PADI Altitude Diver est faite pour vous.",
      "Apprendre à ajuster la planification de votre plongée à la pression ambiante réduite en altitude est une partie importante du cours. Vous ferez deux plongées et apprendrez :",
      "Aussi, la première plongée de cette Spécialité PADI peut être validée comme Plongée Adventure Dive pour votre brevet Advanced Open Water Diver – demandez nous pour obtenir le crédit de la plongée."
    ],
    "introList": [
      "La planification, l’organisation, les procédures et les techniques de la plongée en altitude.",
      "Comment régler votre ordinateur de plongée pour l’altitude ou calculer les profils de la plongée en altitude en utilisant la table RDP ou l’eRDPMLTM.",
      "Comment éviter les problèmes et gérer les situations d’urgence en altitude, si elles se présentent."
    ],
    "included": [
      "Kit pédagogique",
      "2 plongées en milieu naturel",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Plongée en altitude",
        "amount": "CHF 290"
      }
    ],
    "image": "images/courses/padi-plongee-en-altitude.webp"
  },
  "/formations-loisirs/specialites-padi/padi-plongee-sous-glace": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-combinaison-etanche",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite"
    ],
    "videoId": "GqNucOMUGes",
    "intro": [
      "Si vous avez l’esprit d’aventure, de l’insolite et aimez les plongées défiantes, alors essayez la plongée sous glace. Pendant le cours, accompagné d’un Professionnel PADI, vous plongerez dans une des aventures les plus extrêmes que la plongée-loisir peut offrir.",
      "Vous ferez un minimum de trois plongées de formation sous glace dans le cadre de votre brevet. Les plongées sont organisées avec un groupe de personnes qui travaillent ensemble comme aides, plongeurs, sécurité de surface, plongeurs de sécurité. Sous la glace, vous apprendrez la maîtrise de la flottabilité, l’orientation sous- marine et à garder le contact avec les guides sous l’eau et en surface par l’intermédiaire des signes et de tractions sur des lignes.",
      "Vous apprendrez :"
    ],
    "introList": [
      "La panification et organisation de plongées sous glace.",
      "Les raisons et opportunités de plonger sous glace.",
      "Les considérations sur le matériel.",
      "La sélection des sites, préparation et découpe de la glace.",
      "Les procédures et techniques pour gérer les problèmes et risques de la plongée sous glace.",
      "L’utilisation de l’équipement spécifique, lignes de vie, signaux, communication, procédures d’utilisation des lignes de sécurité.",
      "La gestion des problèmes de matériel",
      "Les effets du froid, les procédures d’urgence et de sécurité."
    ],
    "included": [
      "Théorie",
      "3 plongées en milieu naturel",
      "Équipement de plongée",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Plongée Sous Glace",
        "amount": "CHF 390"
      }
    ],
    "image": "images/courses/padi-plongee-sous-glace.webp",
    "cardImage": "images/courses/card-padi-plongee-sous-glace.webp"
  },
  "/formations-loisirs/specialites-padi/padi-parachute-de-palier": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-plongee-sur-epave",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite"
    ],
    "videoId": "vmjVQs-ee5E",
    "intro": [
      "De nombreux plongeurs ne songeraient jamais à plonger sans avoir sur eux un parachute de palier et, dans certaines régions, c’est considéré comme une pièce d’équipement de sécurité obligatoire.",
      "Les bateaux et les courants sont deux facteurs fréquemment associés à de nombreux sites de plongée. Les plaisanciers ne localisent pas toujours des plongeurs aux alentours et le courant peut les emporter plus loin que prévu. Déployer un parachute de palier avant de faire surface prévient les autres de votre localisation avant votre remontée. Autre facteur lié à la sécurité, vous pouvez aussi utiliser le bout de votre parachute pour vous aider à faire votre palier de sécurité, ce qui est pratique en présence de courants ou lorsqu’il n’y a pas d’autre référence visuelle.",
      "Pendant les deux plongées de formation, vous pratiquerez :",
      "Aussi, la première plongée de cette Spécialité PADI peut être validée comme Plongée Adventure Dive pour votre brevet Advanced Open Water Diver – demandez nous pour obtenir le crédit de la plongée."
    ],
    "introList": [
      "Préparer et ranger votre parachute et dévidoir.",
      "Déployer votre parachute dans une position statique et en pleine eau.",
      "Nager tout en tractant un parachute et gérer le dévidoir et le bout.",
      "Faire un palier de sécurité en utilisant le parachute."
    ],
    "included": [
      "Théorie",
      "2 plongées en milieu naturel",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Parachute de palier",
        "amount": "CHF 300"
      }
    ],
    "image": "images/courses/padi-parachute-de-palier.webp",
    "cardImage": "images/courses/card-padi-parachute-de-palier.webp"
  },
  "/formations-loisirs/specialites-padi/padi-plongee-sur-epave": {
    "related": [
      "/formations-loisirs/specialites-padi/padi-plongee-profonde",
      "/formations-loisirs/specialites-padi/padi-plongee-de-nuit"
    ],
    "videoId": "vmjVQs-ee5E",
    "intro": [
      "Les navires, les avions et même les voitures, sont fascinants à explorer et regorgent généralement de vie aquatique. Chaque plongée sur épave est l’occasion d’une nouvelle découverte.",
      "Que ce soient des épaves immergées volontairement comme récifs artificiels pour les plongeurs, ou coulées à la suite d’un accident, elles sont des témoignages fascinants du passé. Les épaves de bateaux, d’avions et même de voitures sont palpitantes à explorer et abondent généralement de vie aquatique. Chacune est une opportunité de découverte, cachant potentiellement un mystère ou espionnant quelque chose que d’autres ont manqué. La Spécialité Plongée sur épave PADI (Wreck Diver) est populaire parce qu’elle offre des aventures enrichissantes tout en observant les pratiques responsables de la plongée sur épave.",
      "Il existe de nombreux types d’épaves, et certaines sont protégées par des lois qui défendent leurs valeurs historique et culturelle. Votre formation commence par l’étude des directives sur la recherche et la protection des épaves. Lors de quatre plongées, vous apprendrez :",
      "Aussi, la première plongée de cette Spécialité PADI peut être validée comme Plongée Adventure Dive pour votre brevet Advanced Open Water Diver – demandez nous pour obtenir le crédit de la plongée."
    ],
    "introList": [
      "Les considérations de sécurité liées à la navigation sur épaves et à leur exploration.",
      "À faire des recherches sur une épave et à dessiner une carte.",
      "À utiliser des fils d’Ariane et des dévidoirs pour guider votre exploration.",
      "Les techniques de palmage pour éviter de soulever les sédiments ou de fragiliser l’épave et de perturber ses habitants."
    ],
    "included": [
      "Théorie",
      "4 plongées en milieu naturel",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Plongée sur épave",
        "amount": "CHF 400"
      }
    ],
    "image": "images/courses/padi-plongee-sur-epave.webp",
    "cardImage": "images/courses/card-padi-plongee-sur-epave.webp"
  },
  "/formations-loisirs/remise-a-niveau/padi-reactivate-piscine": {
    "related": [
      "/formations-loisirs/avances/padi-advanced-open-water-diver",
      "/formations-loisirs/specialites-padi/padi-combinaison-etanche",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite"
    ],
    "videoId": "KHe977_DW7A",
    "intro": [
      "Mettez à jour vos compétences et vos connaissances en plongée avec un rapide rappel du cours PADI Open Water Diver avant de vous remettre à l’eau.",
      "Cela fait un bout de temps que vous n’avez pas plongé et vous souhaitez une remise à niveau rapide ? Avant de plonger à nouveau, le programme PADI ReActivate TM est le moyen idéal pour mettre à jour les connaissances et les techniques de plongée du cours PADI Open Water Diver.",
      "Que vous désiriez uniquement quelques rappels, ou souhaitiez revoir les bases, ReActivate s’adapte à vos besoins. Vous révisez les concepts de plongée à votre aise sur votre tablette, votre appareil mobile ou votre ordinateur, et ensuite vous plongez avec un Professionnel PADI. C’est rapide et facile, et c’est une bonne façon de vous préparer à votre prochain cours PADI ou à vos prochaines vacances de plongée. En outre, les plongeurs qui complètent la révision des connaissances ainsi que la remise à niveau des techniques de plongée dans l’eau reçoivent une carte de certification de remplacement mentionnant la date de validité de ReActivate.",
      "Tout plongeur certifié désirant une remise à niveau ou une mise à jour avant un voyage devrait se ReActiver. Les centres de plongée aiment voir une date récente ReActivate sur votre carte de certification, car cela signifie que vous êtes prêt à plonger."
    ],
    "included": [
      "Introduction théorique",
      "1 entrée en piscine* (sur Genève seulement)",
      "Nouvelle certification"
    ],
    "prices": [
      {
        "label": "PADI ReActivate (Piscine)",
        "amount": "CHF 200",
        "note": "Plongée additionnelle lac : - CHF 100 en humide - CHF 150 en étanche"
      }
    ],
    "image": "images/courses/padi-reactivate-piscine.webp",
    "cardImage": "images/courses/card-padi-reactivate-piscine.webp"
  },
  "/formations-loisirs/remise-a-niveau/refresh-en-lac": {
    "related": [
      "/formations-loisirs/avances/padi-advanced-open-water-diver",
      "/formations-loisirs/specialites-padi/padi-combinaison-etanche",
      "/formations-loisirs/specialites-padi/padi-maitrise-de-la-flottabilite"
    ],
    "videoId": "KHe977_DW7A",
    "intro": [
      "Vous êtes plongeur certifié et cela fait un bout de temps que vous n’avez pas plongé en milieu naturel. Vous souhaitez une remise à niveau rapide ? Alors ce programme est fait pour vous !",
      "Avant de plonger à nouveau, le Refresh en lac est le moyen idéal pour mettre à jour les connaissances et les techniques de plongée. Que vous désiriez uniquement quelques petits rappels, revoir les bases, travailler votre flottabilité ou même votre lâché de parachute, nous nous adaptons à vos besoins. Faites une plongée Refresh en lac et vous serez prêt à plonger en toute sécurité lors de vos prochaines vacances.",
      "Tout plongeur certifié désirant une remise à niveau ou une mise à jour avant un voyage devrait se ReActiver. Les centres de plongée aiment voir une date récente sur votre carnet de plongées, car cela signifie que vous êtes prêt à plonger."
    ],
    "included": [
      "Introduction théorique",
      "1 plongée en milieu naturel"
    ],
    "prices": [
      {
        "label": "Refresh en Lac « en combinaison humide »",
        "amount": "CHF 120"
      },
      {
        "label": "Refresh en Lac « en combinaison étanche »",
        "amount": "CHF 150"
      }
    ],
    "image": "images/courses/refresh-en-lac.webp"
  },
  "/formations-pro/padi-divemaster": {
    "related": [
      "/formations-pro/padi-open-water-scuba-instructor-idc",
      "/formations-pro/padi-master-scuba-diver-trainer"
    ],
    "videoId": "YE26EF5fy6Y",
    "intro": [
      "S oyez un leader qui guide et motive les autres. Développez vos connaissances et vos capacités de supervision en plongée afin de devenir un modèle pour les plongeurs dans le monde entier.",
      "Le Divemaster est le premier niveau professionnel de la plongée chez PADI. Cette formation vous prépare à organiser, diriger, accompagner et guider des plongées ainsi qu’à travailler étroitement avec les Instructeurs PADI et les assister lors de formations. Le Divemaster est un modèle et un exemple à suivre pour nos plongeurs et élèves. Vous apprendrez entre autres la pédagogie de l’enseignement ainsi que les méthodes d’encadrement.",
      "Description",
      "Le cours de PADI Divemaster vous apprend à devenir un leader et à prendre en charge les activités de plongée. Pendant les séances théoriques, les exercices de compétence aquatique, les ateliers et l’évaluation d’application pratique, vous développez les techniques pour organiser et diriger une variété d’activités de plongée. Les sujets et les ateliers pratiques sont, notamment :",
      "Assurance : l’assurance est du ressort du participant. Nous conseillons l’adhésion à DAN Europe."
    ],
    "introList": [
      "Rôle et caractéristiques du Divemaster PADI.",
      "Supervision des activités générales de plongée et assistant pendant la formation.",
      "Sécurité des plongeurs et gestion des risques.",
      "Programmes dirigés par un Divemaster et activités spécialisées.",
      "Commerce de la plongée et votre carrière en plongée.",
      "Connaissance de l’environnement en plongée.",
      "Préparer et gérer une plongée.",
      "Cartographier un site de plongée en milieu naturel.",
      "Diriger des briefings de plongée.",
      "Organiser un projet de recherche et récupération d’objets et une plongée profonde.",
      "Diriger un programme de remise à niveau ReActivate et un cours de plongée libre Skin Diver.",
      "Faire fonction d’assistant pendant des programmes Discover Scuba Diving et diriger des programmes Discover Local Diving."
    ],
    "included": [
      "Théorique de la plongée",
      "Ateliers en milieu protégé et naturel",
      "Évaluation des techniques de sauvetage",
      "Évaluation des techniques de plongée",
      "Test d’endurance aquatique"
    ],
    "prices": [
      {
        "label": "Divemaster Standard",
        "amount": "CHF 1'400"
      },
      {
        "label": "Divemaster DSD Leader",
        "amount": "CHF 1'600"
      }
    ],
    "image": "images/courses/padi-divemaster.webp"
  },
  "/formations-pro/padi-open-water-scuba-instructor-idc": {
    "related": [
      "/formations-pro/padi-master-scuba-diver-trainer",
      "/formations-pro/padi-idc-staff-instructor",
      "/secourisme/padi-efr-instructor"
    ],
    "videoId": "Euwjer0iSJk",
    "intro": [
      "Le cours complet pour devenir un instructeur PADI ! L’IDC (Instructor Development Course) est la formation de moniteur de plongée PADI.",
      "Description",
      "Si vous aimez les gens, que vous êtes passionné par la plongée et souhaitez une vie extraordinaire – devenez Instructeur PADI. Enseigner la plongée vous permet de partager votre passion du monde aquatique avec les autres tout en faisant ce que vous aimez : être dans l’eau. Les instructeurs PADI Open Water Scuba Instructor et les assistants instructeurs PADI sont les professionnels de la plongée les plus recherchés dans le monde parce qu’ils ont complété le programme qui établit les standards de formation des professionnels de plongée.",
      "La formation à l’instructeur (Instructor Development Course – IDC) est composée de deux parties – le cours d’Assistant Instructor (AI) et le programme Open Water Scuba Instructor (OWSI). La plupart des professionnels de plongée suivent un IDC complet et participent ensuite à un examen d’instructeur (IE), l’étape finale pour acquérir une certification d’Instructeur PADI.",
      "Les professionnels de plongée détenant une qualification d’instructeur d’une autre organisation reconnue de formation de plongeurs peuvent s’inscrire directement au programme OWSI. Cette reconnaissance de leur formation préalable d’instructeur est un accès pour devenir Instructeur PADI.",
      "Académique",
      "Pendant l’IDC, un programme qui se déroule sur cinq jours minimums, mais plus souvent sur sept, vous apprenez à diriger tous les cours de base PADI. Vous apprendrez à organiser et à présenter les informations théoriques, à diriger des séances de développement des techniques et à contrôler les plongées en milieu naturel. En fait, vous devenez un meilleur orateur public, très compétent pour démontrer les exercices, tout en assurant la sécurité des élèves plongeurs. Les principaux sujets comprennent :",
      "Assurance : l’assurance est du ressort du participant. Nous conseillons l’adhésion à DAN Europe ."
    ],
    "introList": [
      "Les Standards et procédures PADI, ainsi que des ateliers dans l’eau pour les cours que vous pouvez enseigner",
      "Apprentissage, enseignement et le Système PADI",
      "Gestion des risques et sécurité du plongeur",
      "Le commerce de la plongée et votre rôle comme instructeur",
      "Marketing de la plongée et Conseils pour améliorer les ventes"
    ],
    "included": [
      "Étude personnelle en eLearning",
      "Ateliers de présentations en milieu protégé et naturel",
      "Évaluation des techniques de sauvetage",
      "Évaluation des techniques de plongée",
      "Test d’endurance aquatique"
    ],
    "prices": [
      {
        "label": "IDC Standard (AI + OWSI)",
        "amount": "CHF 1'500"
      },
      {
        "label": "Assistant Instructeur (AI)",
        "amount": "CHF 900"
      },
      {
        "label": "Open Water Scuba Instructor (OWSI)",
        "amount": "CHF 900"
      },
      {
        "label": "IDC V.I.P. (IDC Standard en cours Privé)",
        "amount": "CHF 2'300"
      }
    ],
    "image": "images/courses/padi-open-water-scuba-instructor-idc.webp",
    "cardImage": "images/courses/card-padi-open-water-scuba-instructor-idc.webp"
  },
  "/formations-pro/padi-master-scuba-diver-trainer": {
    "related": [
      "/formations-pro/padi-idc-staff-instructor"
    ],
    "videoId": "5Ua2iGRZOxo",
    "intro": [
      "Tous les instructeurs PADI ayant certifié au moins 25 plongeurs PADI et ayant obtenu au moins cinq certifications d’instructeur de spécialité PADI peuvent devenir Master Scuba Diver Trainer.",
      "Le niveau Master Scuba Diver Trainer vous distingue des autres instructeurs de plongée parce que vous montrez votre engagement à continuer votre formation de plongée et êtes prêt à aider les autres à continuer également leur formation. De plus vous enseignez des Spécialités – vous ouvrant la porte vers de nombreuses plongées agréables tout en travaillant.",
      "Description",
      "La qualification PADI Master Scuba Diver Trainer vous distingue comme instructeur de plongée prenant au sérieux la formation continue et s’engageant à enseigner une variété de cours. (Les employeurs potentiels apprécient ces caractéristiques). Être MSDT signifie que vous avez l’expérience et les certifications pour offrir toute la formation nécessaire au plongeur pour devenir Master Scuba Diver – le niveau le plus élevé en plongée loisir.",
      "Ce niveau est l’étape suivante dans l’échelle professionnelle, c’est aussi une condition pré requise pour l’IDC Staff Instructor ainsi que pour de nombreux niveaux de TecRec Instructor.",
      "Vous n’en êtes pas encore là ? Demandez-nous les informations sur le stage pré Master Scuba Diver Trainer.",
      "Spécialités proposées",
      "Plongée profonde, Nitrox, Combinaison étanche, Orientation sous-marine, Plongée de nuit, Recherche et récupération d’objets, Plongée en altitude, Plongée sous-glace, Photographie sous-marine, Plongée depuis un bateau, Plongée sur épave, Plongée dérivante, Oxygen Provider, Plongée à multiniveaux, Spécialiste matériel, Naturalisme, Project AWARE, Coral Reef Conservation, Identification des poissons.",
      "Assurance : l’assurance est du ressort du participant. Nous conseillons l’adhésion à DAN Europe."
    ],
    "included": [
      "Théorie",
      "Ateliers de présentations en milieu protégé et naturel"
    ],
    "prices": [
      {
        "label": "Spécialité Instructeur (prix à l’unité)",
        "amount": "CHF 150"
      },
      {
        "label": "Pack 5 spécialités au choix",
        "amount": "CHF 600"
      }
    ],
    "image": "images/courses/padi-master-scuba-diver-trainer.webp",
    "cardImage": "images/courses/card-padi-master-scuba-diver-trainer.webp"
  },
  "/formations-pro/padi-idc-staff-instructor": {
    "related": [
      "/secourisme/padi-efr-instructor"
    ],
    "videoId": "5Ua2iGRZOxo",
    "intro": [
      "En plus, vous assisterez à un IDC ou apprendrez à enseigner de nombreux composants du programme.",
      "En tant qu’IDC Staff Instructor, vous pouvez enseigner indépendamment les cours d’Assistant Instructeur PADI et fonctionner comme assistant pendant les IDC et d’autres cours de formation continue au niveau instructeur.",
      "Assurance : l’assurance est du ressort du participant. Nous conseillons l’adhésion à DAN Europe ."
    ],
    "introList": [
      "Standards, procédures et contenu du programme de formation d’Instructeur",
      "Comment organiser et diriger le cours d’Assistant Instructeur PADI",
      "Psychologie de l’évaluation et du conseil",
      "Évaluer les présentations pédagogiques en classe, en milieu protégé et en milieu naturel"
    ],
    "included": [
      "Étude personnelle en eLearning",
      "Ateliers pratique en classe et dans l’eau",
      "Participation à un IDC complet"
    ],
    "prices": [
      {
        "label": "PADI IDC Staff Instructor",
        "amount": "CHF 1'000"
      }
    ],
    "image": "images/courses/padi-idc-staff-instructor.webp",
    "cardImage": "images/courses/card-padi-idc-staff-instructor.webp"
  },
  "/formations-tec/padi-discover-tec-diving": {
    "related": [
      "/formations-tec/padi-tec-sidemount",
      "/formations-tec/padi-tec-40",
      "/formations-tec/padi-tec-45",
      "/formations-tec/padi-tec-50"
    ],
    "videoId": "8HimPymlYNg",
    "intro": [
      "La plongée technique (Tec) vous tente, mais vous n’êtes pas sûr de vouloir vous inscrire à un cours ? Le programme Discover Tec vous permet d’essayer la plongée technique via une expérience en milieu protégé.",
      "Notre instructeur Tec vous expliquera l’équipement que vous utiliserez et passera en revue les procédures de base de la plongée tec, telles que l’importance de la plongée en équipe. Avant de vous mettre à l’eau, nous effectuons des ajustements d’équipement pour vous sentir à l’aise avec l’équipement.",
      "Si vous êtes intéressé par la plongée Tec et êtes PADI Open Water Diver , avez au moins 18 ans et avez enregistré au moins 10 plongées, vous vous qualifiez pour participer au programme Discover Tec."
    ],
    "included": [
      "Introduction théorique",
      "1 Entrée et plongée en piscine* (sur Genève seulement)",
      "Équipement de plongée"
    ],
    "prices": [
      {
        "label": "PADI Discover Tec Diving",
        "amount": "CHF 120"
      }
    ],
    "image": "images/courses/padi-discover-tec-diving.webp"
  },
  "/formations-tec/padi-tec-40": {
    "related": [
      "/formations-tec/padi-tec-sidemount",
      "/formations-tec/padi-tec-45",
      "/formations-tec/padi-tec-50"
    ],
    "videoId": "dIcKIpqcHDI",
    "intro": [
      "Lors de cette formation, vous apprendrez à utiliser un logiciel de décompression et des ordinateurs de plongée air, Nitrox ou multigaz, pour planifier et réaliser des plongées à une profondeur maximale de 40 mètres et avec décompression ne dépassant pas 10 minutes. Vous utiliserez une bouteille avec un seul mélange jusqu’à 50% d’oxygène (AENx50) pour la décompression afin d’augmenter la sécurité lors de la décompression nécessaire.",
      "Pour participer au cours de Tec 40, l’élève plongeur doit être certifié Advanced Open Water PADI, PADI Enriched Air Diver (Nitrox), PADI Deep Diver (ou détenir des qualifications reconnues d’une autre organisation de formation), avoir un minimum de 30 plongées enregistrées dont au moins 10 plongées à l’air enrichi d’une profondeur supérieure à 18 mètres.",
      "Cette formation comprend de l’équipement spécifique de plongée, une carte de certification PADI Tec 40 et un kit pédagogique. Vous continuerez à utiliser le manuel Tec Deep Diver jusqu’au Tec 50."
    ],
    "included": [
      "1 Plongée en milieu protégé",
      "3 Plongées en milieu naturel",
      "Équipement spécifique de plongée Tec",
      "Certification"
    ],
    "prices": [
      {
        "label": "Tec 40 \"Standard\"",
        "amount": "CHF 700"
      },
      {
        "label": "Tec \"Gold\" (40 + 45)",
        "amount": "CHF 1'350"
      },
      {
        "label": "Tec \"Deluxe\" (40 + 45 + 50)",
        "amount": "CHF 2'150"
      }
    ],
    "image": "images/courses/padi-tec-40.webp",
    "cardImage": "images/courses/card-padi-tec-40.webp"
  },
  "/formations-tec/padi-tec-45": {
    "related": [
      "/formations-tec/padi-tec-sidemount",
      "/formations-tec/padi-tec-50"
    ],
    "videoId": "dIcKIpqcHDI",
    "intro": [
      "Cette formation vous permet de compléter vos connaissances techniques de la plongée à décompression et vous emmène plus loin et plus profond. Vous apprendrez à réagir aux urgences prévisibles de la plongée technique.",
      "Pour participer au cours de Tec 45, l’élève plongeur doit être certifié Rescue Diver PADI, PADI Enriched Air Diver (Nitrox), PADI Deep Diver, PADI Tec 40 (ou détenir des qualifications reconnues d’une autre organisation de formation), avoir un minimum de 50 plongées enregistrées dont au moins 12 plongées à l’air enrichi d’une profondeur supérieure à 18 mètres et 6 plongées à une profondeur supérieure à 30 mètres.",
      "Cette formation comprend de l’équipement spécifique de plongée, une carte de certification PADI Tec 45. Vous continuerez à utiliser le manuel Tec Deep Diver reçu lors de la formation Tec 40."
    ],
    "included": [
      "1 Plongée en milieu protégé",
      "3 Plongées en milieu naturel",
      "Équipement spécifique de plongée Tec",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Tec 45",
        "amount": "CHF 800"
      }
    ],
    "image": "images/courses/padi-tec-45.webp",
    "cardImage": "images/courses/card-padi-tec-45.webp"
  },
  "/formations-tec/padi-tec-50": {
    "related": [
      "/formations-tec/padi-tec-sidemount",
      "/formations-tec/padi-tec-trimix-65"
    ],
    "videoId": "dIcKIpqcHDI",
    "intro": [
      "Le cours Tec 50 complète votre formation de plongeur Tec et vous emmène au-delà de la plongée loisir.",
      "Vous ferez des plongées à 50 mètres de profondeur maximum avec décompression réelle. Vous utiliserez de l’air enrichi Nitrox ou de l’oxygène pur pour la décompression et vous apprendrez à utiliser un logiciel de décompression pour créer des tables de plongée personnalisées et planifier vos plongées.",
      "Pour participer au cours de Tec 50, l’élève plongeur doit être certifié Rescue Diver PADI, PADI Enriched Air Diver (Nitrox), PADI Deep Diver, PADI Tec 45 (ou détenir des qualifications reconnues d’une autre organisation de formation), avoir un minimum de 100 plongées enregistrées dont au moins 20 plongées à l’air enrichi, 25 plongées à une profondeur supérieure à 18 mètres et 20 plongées à une profondeur supérieure à 30 mètres.",
      "Cette formation comprend de l’équipement spécifique de plongée, une carte de certification PADI Tec 45. Vous continuerez à utiliser le manuel Tec Deep Diver reçu lors de la formation Tec 40."
    ],
    "included": [
      "1 Plongée en milieu protégé",
      "3 Plongées en milieu naturel",
      "Équipement spécifique de plongée Tec",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Tec 50",
        "amount": "CHF 900"
      }
    ],
    "image": "images/courses/padi-tec-50.webp",
    "cardImage": "images/courses/card-padi-tec-50.webp"
  },
  "/formations-tec/padi-tec-trimix-65": {
    "related": [
      "/formations-tec/padi-tec-sidemount",
      "/formations-tec/padi-tec-trimix",
      "/formations-tec/padi-tec-gas-blender-nitrox"
    ],
    "videoId": "dIcKIpqcHDI",
    "intro": [
      "Ce cours présente les avantages du trimix aux plongeurs et les qualifie pour faire des plongées avec décompression accélérée en utilisant des bouteilles relais multiples à l’AENx et à l’oxygène pur, et à utiliser tout mélange trimix contenant au minimum 18% d’oxygène.",
      "Les plongeurs pourront descendre à une profondeur maximale de 65 mètres.",
      "Le cours PADI Tec Trimix 65 est conçu pour étendre la gamme des profondeurs accessibles par les plongeurs techniques déjà formés et qualifiés à utiliser l’air, l’air enrichi et l’oxygène pur pour des plongées techniques à décompression au-delà de 50 mètres.",
      "Ce cours est destiné aux plongeurs Tec 50 (ou qualification reconnue d’une autre organisation de formation). Le cours améliore vos aptitudes à plonger dans une gamme plus large de profondeurs en vous formant à l’utilisation du trimix (mélange hélium, oxygène et azote)."
    ],
    "included": [
      "Manuel Théorique",
      "Les gaz",
      "1 Plongée en milieu protégé",
      "4 Plongées en milieu naturel",
      "Blocs de déco complets",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Tec Trimix 65",
        "amount": "CHF 1'800"
      }
    ],
    "image": "images/courses/padi-tec-trimix-65.webp",
    "cardImage": "images/courses/card-padi-tec-trimix-65.webp"
  },
  "/formations-tec/padi-tec-trimix": {
    "related": [
      "/formations-tec/padi-tec-sidemount",
      "/formations-tec/padi-tec-gas-blender-nitrox"
    ],
    "videoId": "dIcKIpqcHDI",
    "prices": [
      {
        "label": "PADI Tec Trimix",
        "amount": "CHF 2'200"
      }
    ],
    "image": "images/courses/padi-tec-trimix.webp",
    "cardImage": "images/courses/card-padi-tec-trimix.webp"
  },
  "/formations-tec/padi-tec-sidemount": {
    "related": [
      "/formations-tec/padi-tec-gas-blender-nitrox",
      "/formations-tec/padi-tec-40"
    ],
    "videoId": "dIcKIpqcHDI",
    "intro": [
      "Comme la bouteille de plongée passe de votre dos à vos côtés, instantanément la pression dorsale est éliminée et vous avez davantage de liberté de mouvement pour apprécier plus encore la plongée. Par ailleurs, vous n’avez pas à marcher vers le site de plongée en portant les bouteilles sur le dos. Vous vous mettez à l’eau, les fixer sur vous et vous êtes prêts.",
      "Le cours Tec Sidemount offre les mêmes avantages que le cours Loisir Sidemount Diver, mais il vous donne l’occasion de plonger avec au moins 2 bouteilles pour bénéficier d’un temps de plongée plus long."
    ],
    "introList": [
      "Une manière alternative d’être hydrodynamique sous l’eau.",
      "Un transport de l’équipement hors de l’eau plus facile.",
      "La réduction de la tension sur le bas du dos.",
      "Une réserve de gaz de secours indépendante.",
      "La possibilité de contrôler tout l’équipement puisqu’il se trouve devant vous.",
      "Une plus grande réserve de gaz pour des plongées plus longues."
    ],
    "included": [
      "Théorie",
      "1 Plongée en milieu protégé",
      "4 Plongées en milieu naturel",
      "Équipement de plongée spécifique",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Tec Sidemount",
        "amount": "CHF 600"
      }
    ],
    "image": "images/courses/padi-tec-sidemount.webp",
    "cardImage": "images/courses/card-padi-tec-sidemount.webp"
  },
  "/formations-tec/padi-tec-gas-blender-nitrox": {
    "related": [
      "/formations-tec/padi-tec-sidemount",
      "/formations-tec/padi-tec-40"
    ],
    "videoId": "8HimPymlYNg",
    "included": [
      "Manuel théoriqu",
      "Atelier pratique",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Tec Gas Blender Nitrox",
        "amount": "CHF 300",
        "note": "(CHF 250 si deux élèves)"
      }
    ],
    "image": "images/courses/padi-tec-gas-blender-nitrox.webp",
    "cardImage": "images/courses/card-padi-tec-gas-blender-nitrox.webp"
  },
  "/secourisme/padi-emergency-first-response": {
    "related": [
      "/secourisme/padi-oxygen-provider"
    ],
    "videoId": "z2BAvt9byyM",
    "included": [
      "Théorie",
      "1 atelier pratique",
      "Tout le matériel nécessaire à la réalisation des exercices et scénarios",
      "Certification"
    ],
    "prices": [
      {
        "label": "Pack Standard",
        "amount": "CHF 480",
        "note": "inclus EFR soins Primaires et soins Secondaires + RCP / DEA"
      },
      {
        "label": "Pack Groupe (tarif par personne)",
        "amount": "CHF 390",
        "note": "à partir de 5 personnes"
      },
      {
        "label": "Pack Spécial",
        "amount": "CHF 650",
        "note": "inclus Pack Standard + Spécialité Oxygen Provider"
      },
      {
        "label": "Remise à niveau",
        "amount": "CHF 180"
      }
    ],
    "image": "images/courses/padi-emergency-first-response.webp",
    "cardImage": "images/courses/card-padi-emergency-first-response.webp"
  },
  "/secourisme/padi-oxygen-provider": {
    "related": [
      "/secourisme/padi-emergency-first-response"
    ],
    "videoId": "fjO2e1qqupg",
    "intro": [
      "Soyez prêt à pouvoir aider votre compagnon de plongée en cas d’urgence en devenant un Emergency Oxygen Provider PADI.",
      "Le manuel Emergency Oxygen Provider PADI est un composant important du programme de formation PADI sur l’oxygénothérapie. Avant la pratique, vous reverrez les explications détaillées sur quand et comment administrer l’oxygène d’urgence. Vous étudierez aussi les considérations de sécurité, le montage et le démontage du matériel d’oxygénothérapie. La carte “Soins d’urgence en un coup d’œil”, est un guide pratique que vous pouvez laisser dans votre kit d’oxygénothérapie ou sac de plongée et vous y référer de temps en temps afin d’être prêt en cas d’urgence.",
      "Bien qu’il soit adapté aux plongeurs, le cours n’a pas de pré-requis et n’inclut aucune plongée ; cela signifie que les accompagnateurs – l’équipage du bateau, les amis non plongeurs et le personnel à terre – peuvent également suivre ce cours. Il n’est pas obligatoire d’avoir suivi une formation en RCP ou en premiers secours pour s’inscrire à ce cours."
    ],
    "included": [
      "Une séance théorique",
      "Atelier pratique",
      "Examen théorique",
      "Certification"
    ],
    "prices": [
      {
        "label": "PADI Oxygen Provider",
        "amount": "CHF 300"
      }
    ],
    "image": "images/courses/padi-oxygen-provider.webp",
    "cardImage": "images/courses/card-padi-oxygen-provider.webp"
  },
  "/secourisme/padi-efr-instructor": {
    "related": [
      "/formations-pro/padi-open-water-scuba-instructor-idc",
      "/secourisme/padi-oxygen-provider"
    ],
    "videoId": "z2BAvt9byyM",
    "intro": [
      "Les cours Emergency First Response Instructeur apprennent aux personnes qualifiées la possibilité d’enseigner des cours EFR Soins Primaires (réanimation cardio pulmonaire), Soins Secondaires (premier secours), et Soins pour Enfants.",
      "Les célèbres techniques sur Défibrillateur Externe Automatisé (DEA) sont également abordées. Cette formation renforce les capacités techniques des candidats instructeurs et se concentre sur le développement de leurs aptitudes pédagogiques. Cette formation peut être suivie par toute personne étrangère au milieu de la plongée.",
      "Important : Cette formation est obligatoire pour devenir Instructeur de plongée PADI."
    ],
    "included": [
      "Théorie",
      "Examen théorique",
      "Ateliers pratiques"
    ],
    "prices": [
      {
        "label": "PADI EFR Instructeur",
        "amount": "CHF 500"
      }
    ],
    "image": "images/courses/padi-efr-instructor.webp",
    "cardImage": "images/courses/card-padi-efr-instructor.webp"
  }
};
